# Generated by Django 3.1.4 on 2022-02-08 04:08

import account.models.bankAccount
import account.models.conversionTransaction
import account.models.customerAccount
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('M', 'Manager'), ('C', 'Customer')], default='C', max_length=1)),
                ('state', models.CharField(choices=[('C', 'closed'), ('O', 'unclosed')], default='O', max_length=1)),
                ('balance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('customer_acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account', validators=[account.models.customerAccount.validate_id])),
                ('type', models.CharField(choices=[('P', 'profiting'), ('R', 'regular')], default='R', max_length=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RegularAccount',
            fields=[
                ('regular_acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.customeraccount', validators=[account.models.customerAccount.validate_regular_account_id])),
            ],
        ),
        migrations.CreateModel(
            name='StateConversionTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee', validators=[account.models.conversionTransaction.validate_employee_on_change_account])),
            ],
            options={
                'abstract': False,
                'unique_together': {('account_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account', validators=[account.models.bankAccount.validate_id])),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.manager')),
            ],
        ),
        migrations.CreateModel(
            name='TypeConversionTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customeraccount')),
            ],
            options={
                'abstract': False,
                'unique_together': {('account_id', 'date')},
            },
        ),
    ]
