# Generated by Django 3.1.4 on 2022-02-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(choices=[('C', 'closed'), ('O', 'open')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='stateconversiontransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='typeconversiontransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
