# Generated by Django 3.1.4 on 2022-02-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_deposit_transaction',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='financial.cardtocardtransaction'),
            preserve_default=False,
        ),
    ]
