# Generated by Django 3.1.4 on 2022-02-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_loan_loan_deposit_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtocardtransaction',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depositwithdrawtransaction',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
