# Generated by Django 3.1.4 on 2022-02-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20220209_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtocardtransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='depositwithdrawtransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
