# Generated by Django 3.1.4 on 2022-02-07 10:07

from django.db import migrations, models
import django.db.models.deletion
import user.models.employee.employee


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                    to='user.human', validators=[user.models.employee.validate_id]),
        ),
    ]
