# Generated by Django 3.1.4 on 2022-02-07 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220207_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0)]),
        ),
        migrations.AlterField(
            model_name='human',
            name='nationality_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
