# Generated by Django 3.1.4 on 2022-02-07 11:57

from django.db import migrations, models
import user.models.human.human
import utility.validators


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_auto_20220207_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='birthday_date',
            field=models.DateField(validators=[user.models.human.validate_birthday_date]),
        ),
        migrations.AlterField(
            model_name='human',
            name='nationality_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False,
                                   validators=[utility.validators.FixedLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='human',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1,
                                   validators=[utility.validators.FixedLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='human',
            name='type',
            field=models.CharField(choices=[('E', 'employee'), ('C', 'Customer')], default='C', max_length=1,
                                   validators=[utility.validators.FixedLengthValidator(1)]),
        ),
    ]
